### ISSUE TITLE
Question: .how did you use freecad for this?

### ISSUE THREAD

**Issue by luzpaz** [sunnyerteit/inventasFlow#1]
...asking since this repo is tagged 'freecad'
Pretty cool BTW.

**Comment by sunnyerteit** [comment]
Thanks!

I used FreeCad to establish the geometry. The geometry was later imported to gmsh to generate a mesh.

**Comment by luzpaz** [comment]
@sunnyerteit BTW, are you aware of the existence of: https://github.com/jaheyns/CfdOF/

**Comment by sunnyerteit** [comment]
Sounds very interesting! Will definitely look into for my next cfd project.

**Comment by luzpaz** [comment]
One more thing, @sunnyerteit would you be willing to post this to the FreeCAD [FEM subforum](https://forum.freecadweb.org/viewforum.php?f=18) ?
